# Integrate Fortify on Demand Static AppSec Testing (SAST) into your Circle CI  pipeline
# Renaming this file to config.yml for leveraging the file directly otherwise copy scan job content
# The following environment variables must be defined in CircleCI context before using this job
#   - $FCLI_DEFAULT_FOD_TENANT
#   - $FCLI_DEFAULT_FOD_CLIENT_ID
#   - $FCLI_DEFAULT_FOD_CLIENT_SECRET
#   - $FCLI_DEFAULT_FOD_URL
version: '2.1'
jobs:
  build:
    working_directory: ~/circleci-iwajava
    docker:
      - image: maven:3.8.7-openjdk-18

    steps:
      - checkout

      - restore_cache:
          key: circleci-iwajava-{{ checksum "pom.xml" }}

      - run: mvn package

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-iwajava-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/iwa.jar
          
  scan:
    environment:
      FOD_NOTES: "Triggered by CircleCI Pipeline"
      FOD_RELEASE_ID: <NNNNNNNN>
    working_directory: ~/circleci-iwajava
    docker:
      - image: fortifydocker/fortify-ci-tools:5.4.1-jdk-17

    steps:
      - checkout

      - run: 
          command: |
            echo Setting connection with Fortify Platform
            #Use --insecure switch if the SSL certificate is self generated.
            fcli fod session login

            scancentral package -bt mvn -oss -o package.zip
            fcli fod sast start --release=$FOD_RELEASE_ID --file=package.zip --remediation=NonRemediationScanOnly --notes=$FOD_NOTES --store=Id

            fcli fod sast wait-for ::Id:: --interval=30s
            fcli fod issue list --release=$FOD_RELEASE_ID

            fcli fod session logout

# Orchestrate job run sequence
workflows:
  build_and_scan:
    jobs:
      - build
      - scan:
          context: FOD
          requires:
            - build